# Generated by Django 4.0.4 on 2022-06-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20211125_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=1000),
        ),
    ]
